spring.application.name=housing-management-service
spring.mvc.servlet.path=/housing-management-service
security.jwt.token.key=onBoardingSystem

server.port=0

eureka.instance.hostname=localhost
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
