spring.datasource.url=jdbc:mysql://bfp3.c8jfdelddpc3.us-east-2.rds.amazonaws.com:3306/auth
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=3ode36OP8OCvQHMZuJSh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

security.jwt.token.key=onBoardingSystem
security.jwt.JWT_TOKEN=bearer: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJociIsInBlcm1pc3Npb25zIjpbeyJhdXRob3JpdHkiOiJIUiJ9XSwiZW1wbG95ZWVJZCI6IjY0MDQ2MTJhMWEyYWI1MTMwYzVmOTAwNCJ9.TELHbwYNza9GDxsPCds88Qrf7-OecicUSEWl4e9XyXE

spring.application.name=authentication
spring.mvc.servlet.path=/authentication

server.port=0

eureka.instance.hostname=localhost
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true