#database.hibernate.auth.url=jdbc:mysql://bfp3.c8jfdelddpc3.us-east-2.rds.amazonaws.com:3306/auth
#database.hibernate.auth.driver=com.mysql.cj.jdbc.Driver
#database.hibernate.auth.username=admin
#database.hibernate.auth.password=12345678
#database.hibernate.auth.dialect=org.hibernate.dialect.MySQL5Dialect
#database.hibernate.auth.showsql=true
#
#database.hibernate.application.url=jdbc:mysql://applicationservice.c8jfdelddpc3.us-east-2.rds.amazonaws.com:3306/application
#database.hibernate.application.driver=com.mysql.cj.jdbc.Driver
#database.hibernate.application.username=root
#database.hibernate.application.password=12345678
#database.hibernate.application.dialect=org.hibernate.dialect.MySQL5Dialect
#database.hibernate.application.showsql=true
#
#database.hibernate.housing.url=jdbc:mysql://housingservice.c8jfdelddpc3.us-east-2.rds.amazonaws.com:3306/housing_test
#database.hibernate.housing.driver=com.mysql.cj.jdbc.Driver
#database.hibernate.housing.username=root
#database.hibernate.housing.password=12345678
#database.hibernate.housing.dialect=org.hibernate.dialect.MySQL5Dialect
#database.hibernate.housing.showsql=true

spring.data.mongodb.uri=mongodb+srv://team3:ecRvqP2nMYVrHApt@beaconfire-project-clus.zmyxpdh.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=beaconfire-project-database
spring.data.mongodb.port=27017
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

security.jwt.token.key=onBoardingSystem
