spring.mail.host = smtp-mail.outlook.com
spring.mail.username = rabbitdemo123@outlook.com
spring.mail.password = rabbit123
spring.mail.port = 587
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

spring.application.name=email-service
spring.mvc.servlet.path=/email-service

server.port=0

eureka.instance.hostname=localhost
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

