spring.datasource.url=jdbc:mysql://bfhousing.c8jfdelddpc3.us-east-2.rds.amazonaws.com:3306/housing
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Xk8tMcV7ozYXoG4S8Ilp
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=housing-service
spring.mvc.servlet.path=/housing-service

server.port=0

eureka.instance.hostname=localhost
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

security.jwt.token.key=onBoardingSystem
